"""
BakkesModSDK Python Bindings
============================
CPython bindings for the BakkesMod Rocket League plugin SDK.
"""

from bakkesmod._bindings import (
    # Constants
    BAKKESMOD_PLUGIN_API_VERSION,
    CONST_RadToUnrRot,
    CONST_UnrRotToRad,
    CONST_DegToUnrRot,
    CONST_PI_F,
    CONST_PI_D,

    # Enums
    PLUGINTYPE,
    NOTIFIER_PERMISSION,
    ToastType,
    TRADEHOLD,
    PRODUCTQUALITY,
    UNLOCKMETHOD,
    CARBODY,
    OnlinePlatform,
    Itempaint,
    Equipslot,
    EGuidFormats,
    AttributeType,

    # Core Math Structs
    Vector,
    Rotator,
    Quat,
    Vector2,
    Vector2F,
    LinearColor,
    UnrealColor,

    # Game Data Structs
    ControllerInput,
    RBState,
    PredictionInfo,
    SteamID,
    SkillRating,
    SkillRank,
    ProfileCameraSettings,
    GamepadSettings,
    VideoSettings,
    POV,
    ViewTarget,
    CameraSave,
    WorldContactData,
    WheelContactData,
    StickyForceData,
    ReplayScoreData,
    ProductInstanceID,
    GUIDWrapper,
    TrainingRoundProgress,
    RecordedSample,
    BotLoadoutData,
    CurlRequest,
    FormField,
    FormFieldType,
    PluginInfo,

    # Pluginsdk structs
    TeamPaint,
    CarColors,
    ColorPosition,
    ItemAttribute,
    ItemData,
    Loadout,

    # Math Conversion Free Functions
    VectorToRotator,
    RotatorToVector,
    RotateVectorWithQuat,
    RotatorToQuat,
    QuatToRotator,
    QuatSlerp,

    # Engine Wrappers
    ObjectWrapper,
    ActorWrapper,
    RBActorWrapper,
    PlayerReplicationInfoWrapper,
    PriXWrapper,
    EngineTAWrapper,
    UnrealStringWrapper,
    WorldInfoWrapper,
    EnumWrapper,

    # Player / Controller Wrappers
    PlayerControllerWrapper,
    ControllerWrapper,
    AIControllerWrapper,

    # Game Object Wrappers
    VehicleWrapper,
    CarWrapper,
    BallWrapper,
    PriWrapper,
    CarComponentWrapper,
    BoostWrapper,
    DodgeComponentWrapper,
    JumpComponentWrapper,
    DoubleJumpComponentWrapper,
    FlipCarComponentWrapper,
    AirControlComponentWrapper,
    PrimitiveComponentWrapper,
    VehicleSimWrapper,
    WheelWrapper,
    TeamWrapper,
    GoalWrapper,
    BoostPickupWrapper,
    CameraWrapper,
    CameraXWrapper,
    BaseCameraWrapper,
    CameraSettingsActorWrapper,
    FXActorWrapper,
    ClubDetailsWrapper,
    MapDataWrapper,
    MapListWrapper,
    PhysicalMaterialPropertyWrapper,
    TeamInfoWrapper,
    VehiclePickupWrapper,
    BreakOutActorPlatformWrapper,
    BallBreakoutWrapper,
    BallGodWrapper,
    BallHauntedWrapper,
    GoalHoopsWrapper,

    # Camera State Wrappers
    CameraStateWrapper,
    CameraStateBlenderWrapper,
    CameraStateCarWrapper,
    CameraStateCarRefWrapper,
    CameraStateXWrapper,

    # Rumble Pickup Wrappers
    RumblePickupComponentWrapper,
    AttachmentPickup,
    BallCarSpringPickup,
    BallFreezePickup,
    BallLassoPickup,
    BattarangPickup,
    BoostModPickup,
    BoostOverridePickup,
    CarSpeedPickup,
    DemolishPickup,
    GrapplingHookPickup,
    GravityPickup,
    HandbrakeOverridePickup,
    HitForcePickup,
    SpringPickup,
    SwapperPickup,
    TargetedPickup,
    TimeBombPickup,
    TornadoPickup,
    VelcroPickup,

    # Mesh Component Wrappers
    MeshComponentWrapper,
    CarMeshComponentBaseWrapper,
    SkeletalMeshComponentWrapper,

    # Performance Stats Wrappers
    SampleHistoryWrapper,
    StatGraphWrapper,
    StatGraphSystemWrapper,
    StartGraphSystemWrapper,
    InputBufferGraphWrapper,
    NetStatGraphWrapper,
    PerfStatGraphWrapper,
    SampleRecordSettingsWrapper,
    StatEventWrapper,

    # Game Event Wrappers
    GameEventWrapper,
    TeamGameEventWrapper,
    ServerWrapper,
    ReplayWrapper,
    ReplayDirectorWrapper,
    ReplaySoccarWrapper,
    TrainingEditorWrapper,
    TutorialWrapper,
    GameEditorWrapper,
    GameSettingPlaylistWrapper,
    SaveDataWrapper,
    GameEditorSaveDataWrapper,
    TrainingEditorSaveDataWrapper,

    # Replay Wrappers
    ReplayManagerWrapper,
    ReplayServerWrapper,
    ReplayViewerDataWrapper,

    # Main API
    GameWrapper,
    CVarManagerWrapper,
    CVarWrapper,
    CanvasWrapper,
    MMRWrapper,
    SettingsWrapper,
    UniqueIDWrapper,
    MatchmakingWrapper,
    PluginManagerWrapper,
    GuiManagerWrapper,
    MenuStackWrapper,
    HudWrapper,
    HUDXWrapper,
    HUDTABaseWrapper,
    HUDTAWrapper,
    SpectatorHUDWrapper,
    ImageWrapper,
    HttpWrapper,
    ModalWrapper,
    TextInputModalWrapper,
    GfxDataTrainingWrapper,
    CareerStatsWrapper,

    # Sequence / Kismet
    SequenceWrapper,
    SequenceObjectWrapper,
    SequenceVariableWrapper,
    SequenceOpWrapper,

    # Items
    ItemsWrapper,
    ProductWrapper,
    ProductSlotWrapper,
    OnlineProductWrapper,
    ProductPaintWrapper,
    ProductTemplateWrapper,
    ProductTradeInWrapper,
    TradeWrapper,
    LoadoutWrapper,
    LoadoutSaveWrapper,
    LoadoutSetWrapper,
    LoadingProductWrapper,
    GfxProductsWrapper,
    ProductAttributeWrapper,
    ProductAttribute_AnimatedSkinLabelWrapper,
    ProductAttribute_BlueprintCostWrapper,
    ProductAttribute_BlueprintWrapper,
    ProductAttribute_BodyCompatibilityWrapper,
    ProductAttribute_CertifiedWrapper,
    ProductAttribute_CurrencyWrapper,
    ProductAttribute_PaintedWrapper,
    ProductAttribute_QualityWrapper,
    ProductAttribute_SpecialEditionWrapper,
    ProductAttribute_SpecialEditionSettingsWrapper,
    ProductAttribute_TeamEditionUploadWrapper,
    ProductAttribute_TeamEditionWrapper,
    ProductAttribute_UnlockMethodWrapper,
    CertifiedStatDatabaseWrapper,
    DataAssetDatabaseWrapper,
    DataAssetDatabase_ESportsTeamWrapper,
    PaintDatabaseWrapper,
    SpecialEditionDatabaseWrapper,
)

__all__ = [name for name in dir() if not name.startswith('_')]
